# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: 5aa4039b1cf66eeacaa4a6647635ea94e936d9e531d3646920d978cbf54e19db35b6c583637caeefec05c830ff308b553d055536b8e43a78e8aa0789fd46cc5d

test:
  secret_key_base: 7b8989830ef3df52eca605fea07251e5e4b48b0632d360317eb055ba6ee85b0297a88936c4092d117cff076f31f37aab6fb0fa390d8ed2a8bcee97dc25ea9bd5
=======
  secret_key_base: f08aef5a054f9d0c80a8f65685b848978db0842a313efb92c146c1293fd1dab9dfdc84d8c47d18856a67efacfec497375a9ef8c79858f7603e6506d7e4a663a2

test:
  secret_key_base: db9c28bff51cfe0cf54aaf5bd11af9a5d3b79e71d0f146c9b5c7febd6a7a5215172a57d7b27dd35a9e42cec454f183713ac4aa965ca614ba0a775d963575380e
>>>>>>> acd6bb2bbdbbe808b22c126ddfa908cf8f41f11d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
